### PR TITLE
Update Jenkinsfile

### PR DESCRIPTION
**Pull request by jhunzik**
## What does this PR do?
Remove the push to docker hub as an image is no longer generated. Update jdk version.

## How should it be tested?
A passing CI build

### CODE REVIEW

**Comment by jhunzik** [comment]
build now

**Comment by jhunzik** [comment]
build now

**Comment by mcalcote** [comment]
build now

**Comment by jhunzik** [comment]
build now

**Review by mcalcote — APPROVED** [review]

**Review by figliold — APPROVED** [review]

**Pull request merged**
